# Generated by Django 2.2.1 on 2019-05-09 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('msg_title', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_body', models.TextField()),
                ('msg_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='w3app.Message')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='w3app.Topic')),
            ],
            options={
                'ordering': ('msg_date',),
            },
        ),
        migrations.CreateModel(
            name='BBS_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sysop', models.BooleanField(default=False)),
                ('is_cosysop', models.BooleanField(default=False)),
                ('is_31337', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
